In [1]:
import numpy as np

In [21]:
import re


def vector_vector_multiplication(U,v):
    assert U.shape[0] == v.shape[0]
    
    n = U.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result+ U[i] * v[i]
        
    return result
        

In [3]:
u = np.array([2,4,5,6])

v = np.array([1,0,0,2])

In [10]:
vector_vector_multiplication(u,v)

14.0

In [22]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)
    return result

In [13]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [14]:
v = np.array([1,0.5,2,1])

In [23]:
matrix_vector_multiplication(U,v)

array([20. ,  6. ,  8.5])

In [25]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

In [27]:

def matrix_matrix_multiplication(U,v):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows,num_cols))
    
    for i in range(num_cols):
        vi = V[:,i]
        Uvi = matrix_vector_multiplication(U,vi)
        result[:,i] = Uvi
    return result

In [28]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [31]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [37]:
V[[0,1,2]]

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [34]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])